package vn.easycredit.mcc.model;
/**
 * This class was automatically generated by the data modeler tool.
 */
import java.io.Serializable;

public class AddressInfo implements Serializable{
	static final long serialVersionUID = 1L;
    private String nation;
    private String city;
    private String district;
    private String ward;
    private String addressDetails;
	public String getNation() {
		return nation;
	}
	public void setNation(String nation) {
		this.nation = nation;
	}
	public String getCity() {
		return city;
	}
	public void setCity(String city) {
		this.city = city;
	}
	public String getDistrict() {
		return district;
	}
	public void setDistrict(String district) {
		this.district = district;
	}
	public String getWard() {
		return ward;
	}
	public void setWard(String ward) {
		this.ward = ward;
	}
	public String getAddressDetails() {
		return addressDetails;
	}
	public void setAddressDetails(String addressDetails) {
		this.addressDetails = addressDetails;
	}
	public AddressInfo(String nation, String city, String district, String ward, String addressDetails) {
		super();
		this.nation = nation;
		this.city = city;
		this.district = district;
		this.ward = ward;
		this.addressDetails = addressDetails;
	}
	public AddressInfo() {}
}
