package vn.easycredit.mcc.model;
/**
 * This class was automatically generated by the data modeler tool.
 */
import java.io.Serializable;

public class Address implements Serializable{
	 static final long serialVersionUID = 1L;
    private AddressInfo currentAddress;
    private AddressInfo permanentAddress;
	public AddressInfo getCurrentAddress() {
		return currentAddress;
	}
	public void setCurrentAddress(AddressInfo currentAddress) {
		this.currentAddress = currentAddress;
	}
	public AddressInfo getPermanentAddress() {
		return permanentAddress;
	}
	public void setPermanentAddress(AddressInfo permanentAddress) {
		this.permanentAddress = permanentAddress;
	}
	public Address(AddressInfo currentAddress, AddressInfo permanentAddress) {
		super();
		this.currentAddress = currentAddress;
		this.permanentAddress = permanentAddress;
	}
	
	public Address() {}
}
