package vn.easycredit.mcc.model;
/**
 * This class was automatically generated by the data modeler tool.
 */
import java.io.Serializable;

public class Company implements Serializable {
	 static final long serialVersionUID = 1L;
    private String jobType;
    private String jobTitle;
    private String companyName;
    private String nation;
    private String city;
    private String district;
    private String ward;
    private String addressDetails;
    private String currentWorkplacePhoneNumber;
	public String getJobType() {
		return jobType;
	}
	public void setJobType(String jobType) {
		this.jobType = jobType;
	}
	public String getJobTitle() {
		return jobTitle;
	}
	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}
	public String getCompanyName() {
		return companyName;
	}
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}
	public String getNation() {
		return nation;
	}
	public void setNation(String nation) {
		this.nation = nation;
	}
	public String getCity() {
		return city;
	}
	public void setCity(String city) {
		this.city = city;
	}
	public String getDistrict() {
		return district;
	}
	public void setDistrict(String district) {
		this.district = district;
	}
	public String getWard() {
		return ward;
	}
	public void setWard(String ward) {
		this.ward = ward;
	}
	public String getAddressDetails() {
		return addressDetails;
	}
	public void setAddressDetails(String addressDetails) {
		this.addressDetails = addressDetails;
	}
	public String getCurrentWorkplacePhoneNumber() {
		return currentWorkplacePhoneNumber;
	}
	public void setCurrentWorkplacePhoneNumber(String currentWorkplacePhoneNumber) {
		this.currentWorkplacePhoneNumber = currentWorkplacePhoneNumber;
	}
	public Company(String jobType, String jobTitle, String companyName, String nation, String city, String district,
			String ward, String addressDetails, String currentWorkplacePhoneNumber) {
		super();
		this.jobType = jobType;
		this.jobTitle = jobTitle;
		this.companyName = companyName;
		this.nation = nation;
		this.city = city;
		this.district = district;
		this.ward = ward;
		this.addressDetails = addressDetails;
		this.currentWorkplacePhoneNumber = currentWorkplacePhoneNumber;
	}
	public Company() {}
}
