package vn.easycredit.mcc.model;
/**
 * This class was automatically generated by the data modeler tool.
 */
import java.io.Serializable;

public class Contact implements Serializable{
	 static final long serialVersionUID = 1L;
    private String otherContact;
    private String contactDetail;
    private String mailingAddress;
    private String email;
    private String currentCity;
    private String provinceOfResidence;
    private String employment;
	public String getOtherContact() {
		return otherContact;
	}
	public void setOtherContact(String otherContact) {
		this.otherContact = otherContact;
	}
	public String getContactDetail() {
		return contactDetail;
	}
	public void setContactDetail(String contactDetail) {
		this.contactDetail = contactDetail;
	}
	public String getMailingAddress() {
		return mailingAddress;
	}
	public void setMailingAddress(String mailingAddress) {
		this.mailingAddress = mailingAddress;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getCurrentCity() {
		return currentCity;
	}
	public void setCurrentCity(String currentCity) {
		this.currentCity = currentCity;
	}
	public String getProvinceOfResidence() {
		return provinceOfResidence;
	}
	public void setProvinceOfResidence(String provinceOfResidence) {
		this.provinceOfResidence = provinceOfResidence;
	}
	public String getEmployment() {
		return employment;
	}
	public void setEmployment(String employment) {
		this.employment = employment;
	}
	public Contact() {}
	public Contact(String otherContact, String contactDetail, String mailingAddress, String email, String currentCity,
			String provinceOfResidence, String employment) {
		super();
		this.otherContact = otherContact;
		this.contactDetail = contactDetail;
		this.mailingAddress = mailingAddress;
		this.email = email;
		this.currentCity = currentCity;
		this.provinceOfResidence = provinceOfResidence;
		this.employment = employment;
	}
    

}
