package vn.easycredit.mcc.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DecisionResult implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String result;
	private java.lang.Integer internalScore;
	private java.lang.Double anuity;

	private java.lang.String subcode;

	private java.lang.Double offer;

	private java.lang.String endProcess;

	private Double totalRevenue;

	public DecisionResult() {
	}

	public java.lang.String getResult() {
		return this.result;
	}

	public void setResult(java.lang.String result) {
		this.result = result;
	}

	public java.lang.Integer getInternalScore() {
		return this.internalScore;
	}

	public void setInternalScore(java.lang.Integer internalScore) {
		this.internalScore = internalScore;
	}

	public java.lang.Double getAnuity() {
		return this.anuity;
	}

	public void setAnuity(java.lang.Double anuity) {
		this.anuity = anuity;
	}

	public java.lang.String getSubcode() {
		return this.subcode;
	}

	public void setSubcode(java.lang.String subcode) {
		this.subcode = subcode;
	}

	public java.lang.Double getOffer() {
		return this.offer;
	}

	public void setOffer(java.lang.Double offer) {
		this.offer = offer;
	}

	public java.lang.String getEndProcess() {
		return this.endProcess;
	}

	public void setEndProcess(java.lang.String endProcess) {
		this.endProcess = endProcess;
	}

	public java.lang.Double getTotalRevenue() {
		return this.totalRevenue;
	}

	public void setTotalRevenue(java.lang.Double totalRevenue) {
		this.totalRevenue = totalRevenue;
	}

	public DecisionResult(java.lang.String result,
			java.lang.Integer internalScore, java.lang.Double anuity,
			java.lang.String subcode, java.lang.Double offer,
			java.lang.String endProcess, java.lang.Double totalRevenue) {
		this.result = result;
		this.internalScore = internalScore;
		this.anuity = anuity;
		this.subcode = subcode;
		this.offer = offer;
		this.endProcess = endProcess;
		this.totalRevenue = totalRevenue;
	}

}