package vn.easycredit.mcc.model;
/**
 * This class was automatically generated by the data modeler tool.
 */
import java.io.Serializable;

public class Disbursement implements Serializable {
	 static final long serialVersionUID = 1L;
    private  String loanPurpose;
    private  String method;
    private  String nameOfBeneficiary;
    private  String beneficiaryBank;
    private  String city;
    private  String bankBranch;
    private  String bankAccountNumber;
    public Disbursement() {}
	public Disbursement(String loanPurpose, String method, String nameOfBeneficiary, String beneficiaryBank,
			String city, String bankBranch, String bankAccountNumber) {
		super();
		this.loanPurpose = loanPurpose;
		this.method = method;
		this.nameOfBeneficiary = nameOfBeneficiary;
		this.beneficiaryBank = beneficiaryBank;
		this.city = city;
		this.bankBranch = bankBranch;
		this.bankAccountNumber = bankAccountNumber;
	}
	public String getLoanPurpose() {
		return loanPurpose;
	}
	public void setLoanPurpose(String loanPurpose) {
		this.loanPurpose = loanPurpose;
	}
	public String getMethod() {
		return method;
	}
	public void setMethod(String method) {
		this.method = method;
	}
	public String getNameOfBeneficiary() {
		return nameOfBeneficiary;
	}
	public void setNameOfBeneficiary(String nameOfBeneficiary) {
		this.nameOfBeneficiary = nameOfBeneficiary;
	}
	public String getBeneficiaryBank() {
		return beneficiaryBank;
	}
	public void setBeneficiaryBank(String beneficiaryBank) {
		this.beneficiaryBank = beneficiaryBank;
	}
	public String getCity() {
		return city;
	}
	public void setCity(String city) {
		this.city = city;
	}
	public String getBankBranch() {
		return bankBranch;
	}
	public void setBankBranch(String bankBranch) {
		this.bankBranch = bankBranch;
	}
	public String getBankAccountNumber() {
		return bankAccountNumber;
	}
	public void setBankAccountNumber(String bankAccountNumber) {
		this.bankAccountNumber = bankAccountNumber;
	}
    
    

}
