package vn.easycredit.mcc.model;
/**
 * This class was automatically generated by the data modeler tool.
 */
import java.io.Serializable;

public class Info implements Serializable{
	 static final long serialVersionUID = 1L;
}
