package vn.easycredit.mcc.model;
/**
 * This class was automatically generated by the data modeler tool.
 */
import java.io.Serializable;


public class Job implements Serializable{
	static final long serialVersionUID = 1L;
    private String typesOfEmploymentContract;
    private String from;
    private String to;
    private String contractTerm;
    private String taxIdForSelfEmloyedCustomers;
    private String methodOfReceivingSalary;
    private String frequencyOfReceviningSalary;
    private String dateOfReceivingSalary;

    private Company company;
    
  
    public Job() {}

	public Job(String typesOfEmploymentContract, String from, String to, String contractTerm,
			String taxIdForSelfEmloyedCustomers, String methodOfReceivingSalary, String frequencyOfReceviningSalary,
			String dateOfReceivingSalary, Company company) {
		super();
		this.typesOfEmploymentContract = typesOfEmploymentContract;
		this.from = from;
		this.to = to;
		this.contractTerm = contractTerm;
		this.taxIdForSelfEmloyedCustomers = taxIdForSelfEmloyedCustomers;
		this.methodOfReceivingSalary = methodOfReceivingSalary;
		this.frequencyOfReceviningSalary = frequencyOfReceviningSalary;
		this.dateOfReceivingSalary = dateOfReceivingSalary;
		this.company = company;
	}

	public String getTypesOfEmploymentContract() {
		return typesOfEmploymentContract;
	}

	public void setTypesOfEmploymentContract(String typesOfEmploymentContract) {
		this.typesOfEmploymentContract = typesOfEmploymentContract;
	}

	public String getFrom() {
		return from;
	}

	public void setFrom(String from) {
		this.from = from;
	}

	public String getTo() {
		return to;
	}

	public void setTo(String to) {
		this.to = to;
	}

	public String getContractTerm() {
		return contractTerm;
	}

	public void setContractTerm(String contractTerm) {
		this.contractTerm = contractTerm;
	}

	public String getTaxIdForSelfEmloyedCustomers() {
		return taxIdForSelfEmloyedCustomers;
	}

	public void setTaxIdForSelfEmloyedCustomers(String taxIdForSelfEmloyedCustomers) {
		this.taxIdForSelfEmloyedCustomers = taxIdForSelfEmloyedCustomers;
	}

	public String getMethodOfReceivingSalary() {
		return methodOfReceivingSalary;
	}

	public void setMethodOfReceivingSalary(String methodOfReceivingSalary) {
		this.methodOfReceivingSalary = methodOfReceivingSalary;
	}

	public String getFrequencyOfReceviningSalary() {
		return frequencyOfReceviningSalary;
	}

	public void setFrequencyOfReceviningSalary(String frequencyOfReceviningSalary) {
		this.frequencyOfReceviningSalary = frequencyOfReceviningSalary;
	}

	public String getDateOfReceivingSalary() {
		return dateOfReceivingSalary;
	}

	public void setDateOfReceivingSalary(String dateOfReceivingSalary) {
		this.dateOfReceivingSalary = dateOfReceivingSalary;
	}

	public Company getCompany() {
		return company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}
    
    
}
