package vn.easycredit.mcc.model;


/**
 * This class was automatically generated by the data modeler tool.
 */
import java.io.Serializable;
public class Reference implements  Serializable{
	static final long serialVersionUID = 1L;
    public ReferenceInfo getReference1() {
		return reference1;
	}
	public void setReference1(ReferenceInfo reference1) {
		this.reference1 = reference1;
	}
	public ReferenceInfo getReference2() {
		return reference2;
	}
	public void setReference2(ReferenceInfo reference2) {
		this.reference2 = reference2;
	}
	private ReferenceInfo reference1;
    private ReferenceInfo reference2;
	public Reference(ReferenceInfo reference1, ReferenceInfo reference2) {
		super();
		this.reference1 = reference1;
		this.reference2 = reference2;
	}
	
	public Reference() {}
    
    
}