package vn.easycredit.mcc.model;

/**
 * This class was automatically generated by the data modeler tool.
 */
import java.io.Serializable;
public class ReferenceInfo implements Serializable {
	 static final long serialVersionUID = 1L;
	 private String relationship;
	 private String fullName;
	 private String phoneNumber;
	public String getRelationship() {
		return relationship;
	}
	public void setRelationship(String relationship) {
		this.relationship = relationship;
	}
	public String getFullName() {
		return fullName;
	}
	public void setFullName(String fullName) {
		this.fullName = fullName;
	}
	public String getPhoneNumber() {
		return phoneNumber;
	}
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}
	public ReferenceInfo(String relationship, String fullName, String phoneNumber) {
		super();
		this.relationship = relationship;
		this.fullName = fullName;
		this.phoneNumber = phoneNumber;
	}
	public ReferenceInfo() {} 
	 
}
