package vn.easycredit.mcc.model;
/**
 * This class was automatically generated by the data modeler tool.
 */
public class ResultDmn implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.math.BigDecimal valueNumber;

	public java.lang.String valueString;

	public ResultDmn() {
	}

	public java.math.BigDecimal getValueNumber() {
		return this.valueNumber;
	}

	public void setValueNumber(java.math.BigDecimal valueNumber) {
		this.valueNumber = valueNumber;
	}

	public java.lang.String getValueString() {
		return this.valueString;
	}

	public void setValueString(java.lang.String valueString) {
		this.valueString = valueString;
	}

	public ResultDmn(java.math.BigDecimal valueNumber,
			java.lang.String valueString) {
		this.valueNumber = valueNumber;
		this.valueString = valueString;
	}
	
	

}