package vn.easycredit.mcc.utils;

/**
 * This class was automatically generated by the data modeler tool.
 */

import java.math.BigDecimal;
import java.math.MathContext;

import static java.math.BigDecimal.ONE;
import static java.math.MathContext.DECIMAL64;

public class Util implements java.io.Serializable {

	static MathContext DEFAULT_BIGDECIMAL_CONTEXT = DECIMAL64;
    static final long serialVersionUID = 1L;

    public Util() {
    }
    
    static public BigDecimal test(String p)
    {
        return  new BigDecimal(p);
    }
    static public BigDecimal pmt(BigDecimal intRate, BigDecimal nper, BigDecimal pv) {
		BigDecimal fv = BigDecimal.ZERO;
		int type = 0;
		int DECIMAL_SCALE = DEFAULT_BIGDECIMAL_CONTEXT.getPrecision();
		int DECIMAL_ROUNDING_MODE = DEFAULT_BIGDECIMAL_CONTEXT.getRoundingMode().ordinal();
		BigDecimal numerator = intRate.multiply(((pv.multiply(ONE.add(intRate).pow(nper.intValue()))).add(fv)));
		BigDecimal denominator = (ONE.add(intRate.multiply(BigDecimal.valueOf(type)))).multiply(((ONE.add(intRate)).pow(nper.intValue())).subtract(ONE));
		BigDecimal result = numerator.divide(denominator, DECIMAL_SCALE, DECIMAL_ROUNDING_MODE).negate();
		
		return result.abs();
	}



}